# Generated by Django 4.2.5 on 2025-02-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masafa_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossborder",
            name="consolidated_invoice",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
