# Generated by Django 4.2.5 on 2025-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masafa_app", "0002_crossborder_consolidated_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="exclude_in_inventory_list",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
