# Generated by Django 4.2.5 on 2025-02-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masafa_app", "0004_item_item_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="paid",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
