# Generated by Django 4.2.5 on 2025-03-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masafa_app', '0006_alter_crossborder_consolidated_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used'), ('Mixed', 'Mixed')], default='Used', max_length=255, null=True),
        ),
    ]
