# Reserved keywords and their replacements
reserved_keywords = {
    "class": "custom_class",
    "def": "custom_def",
    "id": "custom_id",
    "if": "custom_if",
    "else": "custom_else",
    "while": "while_loop",
    "for": "for_loop",
    "in": "custom_in",
    "try": "custom_try",
    "except": "custom_except",
    "finally": "custom_finally",
    "with": "custom_with",
    "as": "custom_as",
    "return": "custom_return",
    "break": "custom_break",
    "continue": "custom_continue",
    "from": "custom_from",
    "import": "custom_import",
    "lambda": "custom_lambda",
    "and": "custom_and",
    "or": "custom_or",
    "not": "custom_not",
    "is": "custom_is",
    "None": "custom_none",
    "True": "custom_true",
    "False": "custom_false",
}
